### ISSUE TITLE
Bad types

### ISSUE THREAD

**Issue by TymanWasTaken** [TymanWasTaken/cascade#7]
Because of typescript™, I used a bunch of `any` types, as I couldn't figure out how else to do it. These should be fixed if possible. I also made `options` optional in the `CascadeCommand` constructor, as I wasn't sure how else to allow the ability to construct in the command handler with no args, but still have the options working.
# List of issues that need fixed
- All the `any`'s used
- Optional arguments in the constructors of CascadeCommand, CascadeInhibitor, and CascadeListener

**Comment by ghost** [comment]
The links provided in the body of the issue are not longer valid and redirect to elsewhere, can you update the links?

**Comment by TymanWasTaken** [comment]
Most of the `any` problems can be found by just running `deno lint` (I really need to clean that up), but the optional arguments problems are just in the constructors of CascadeCommand, CascadeInhibitor, and CascadeListener. My problem was I couldn't figure out how to add checking if it was a class **extending** the cascade ones, so I just made the default ones throw an error if there were no options.

**Comment by TymanWasTaken** [comment]
I could probably change a ton of the `any` types to `unknown` so I'll look at that

**Comment by TymanWasTaken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix my bad types](https://trello.com/c/x9g39J3G/7-fix-my-bad-types)

**Comment by ghost** [comment]
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Fix my bad types](https://trello.com/c/x9g39J3G/7-fix-my-bad-types)

Curious as to why you chose Trello over GitHub Projects

**Comment by TymanWasTaken** [comment]
> > ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Fix my bad types](https://trello.com/c/x9g39J3G/7-fix-my-bad-types)
> 
> Curious as to why you chose Trello over GitHub Projects

It just looks nicer and has more features

**Comment by TymanWasTaken** [comment]
I think all of them are fixed so I am closing this
